# Generated by Django 5.2.9 on 2025-12-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
